spring:
  datasource:
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/web'
    username: 'mysql'
    password: 'mysql'

mybatis:
  configuration:
    map-underscore-to-camel-case: true

---
spring.config.activate.on-profile: docker

spring.datasource:
  url: 'jdbc:mysql://mysql:3306/web'
